//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOperaciones.SeguridadWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SeguridadWS.ISeguridadService")]
    public interface ISeguridadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeguridadService/Autenticacion", ReplyAction="http://tempuri.org/ISeguridadService/AutenticacionResponse")]
        WCFSeguridad.Dominio.Usuario Autenticacion(string usu_login, string pass_login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeguridadService/Autenticacion", ReplyAction="http://tempuri.org/ISeguridadService/AutenticacionResponse")]
        System.Threading.Tasks.Task<WCFSeguridad.Dominio.Usuario> AutenticacionAsync(string usu_login, string pass_login);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISeguridadServiceChannel : WebOperaciones.SeguridadWS.ISeguridadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SeguridadServiceClient : System.ServiceModel.ClientBase<WebOperaciones.SeguridadWS.ISeguridadService>, WebOperaciones.SeguridadWS.ISeguridadService {
        
        public SeguridadServiceClient() {
        }
        
        public SeguridadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SeguridadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeguridadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeguridadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFSeguridad.Dominio.Usuario Autenticacion(string usu_login, string pass_login) {
            return base.Channel.Autenticacion(usu_login, pass_login);
        }
        
        public System.Threading.Tasks.Task<WCFSeguridad.Dominio.Usuario> AutenticacionAsync(string usu_login, string pass_login) {
            return base.Channel.AutenticacionAsync(usu_login, pass_login);
        }
    }
}
